import Head from "next/head";
import "../styles/globals.scss";

const MyApp = ({ Component, pageProps }) => {
    return (
        <>
            <Head>
                <title>online-note</title>
                <meta name="description" content="Generated by online-note" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet"
                ></link>
            </Head>
            <Component {...pageProps} />
        </>
    );
};

export default MyApp;
