import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../component/header";

const Home = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>online-note</title>
                <meta
                    name="description"
                    content="Generated by online-note"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Header/>
            </main>
        </div>
    );
}

export default Home